In [1]:
import numpy as np
from numpy import genfromtxt #generates array from text %%file

In [2]:
data = genfromtxt('DATA/bank_note_data.txt', delimiter=',')#It indicates the features are separated by commas

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
labels = data[:,4]#Get all labels from the last column

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:,0:4]#grab everything except last column

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [9]:
x,y = features,labels

In [11]:
#Split the data into train and test data sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.33, random_state = 42)#Pass in features and labels, 33% of the labels and feature
#will be used for testing, and the data is going to be shuffled. 42 is for the randomness to always be the same.

In [12]:
x_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [13]:
len(x_train)

919

In [15]:
# Standardize or scale the data
from sklearn.preprocessing import MinMaxScaler
scaler_object = MinMaxScaler()

In [16]:
scaler_object.fit(x_train)#it lets it know the max and min

MinMaxScaler(copy=True, feature_range=(0, 1))

In [17]:
scaled_x_train = scaler_object.transform(x_train)

In [18]:
scaled_x_test = scaler_object.transform(x_test)

In [19]:
scaled_x_train.max()

1.0000000000000002

In [20]:
x_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [21]:
#Building the model
from keras.models import Sequential
from keras.layers import Dense

In [23]:
model = Sequential()
model.add(Dense(4, input_dim=4, activation='relu'))#4 features,the input dimensions is 4, and the activations function is rectified linear unit, relu
#This is just the input layer

In [27]:
model.add(Dense(8, activation='relu'))#how many neurons. this time, it is twice the inputs. 
model.add(Dense(1, activation='sigmoid'))#Output layer, sigmoid for it to be between 0 and 1

In [28]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [29]:
model.fit(scaled_x_train, y_train, epochs=50, verbose=2) #fit or train the model. 50 epochs, and verbose to see everything

Epoch 1/50
 - 1s - loss: 0.6901 - acc: 0.5495
Epoch 2/50
 - 0s - loss: 0.6792 - acc: 0.5495
Epoch 3/50
 - 0s - loss: 0.6664 - acc: 0.5495
Epoch 4/50
 - 0s - loss: 0.6495 - acc: 0.5495
Epoch 5/50
 - 0s - loss: 0.6337 - acc: 0.5495
Epoch 6/50
 - 0s - loss: 0.6173 - acc: 0.6181
Epoch 7/50
 - 0s - loss: 0.5977 - acc: 0.7029
Epoch 8/50
 - 0s - loss: 0.5749 - acc: 0.7323
Epoch 9/50
 - 0s - loss: 0.5525 - acc: 0.7606
Epoch 10/50
 - 0s - loss: 0.5292 - acc: 0.7911
Epoch 11/50
 - 0s - loss: 0.5064 - acc: 0.8107
Epoch 12/50
 - 0s - loss: 0.4831 - acc: 0.8248
Epoch 13/50
 - 0s - loss: 0.4602 - acc: 0.8433
Epoch 14/50
 - 0s - loss: 0.4379 - acc: 0.8477
Epoch 15/50
 - 0s - loss: 0.4143 - acc: 0.8662
Epoch 16/50
 - 0s - loss: 0.3930 - acc: 0.8683
Epoch 17/50
 - 0s - loss: 0.3700 - acc: 0.8803
Epoch 18/50
 - 0s - loss: 0.3486 - acc: 0.8847
Epoch 19/50
 - 0s - loss: 0.3310 - acc: 0.8857
Epoch 20/50
 - 0s - loss: 0.3094 - acc: 0.8934
Epoch 21/50
 - 0s - loss: 0.2888 - acc: 0.9042
Epoch 22/50
 - 0s - lo

In [30]:
#Now, we test
model.predict_classes(scaled_x_test)

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    

In [32]:
model.metrics_names #We use these metrics to evaluate the model performance

['loss', 'acc']

In [33]:
from sklearn.metrics import confusion_matrix,classification_report

In [34]:
predictions = model.predict_classes(scaled_x_test)

In [35]:
confusion_matrix(y_test,predictions)

array([[254,   3],
       [  5, 191]], dtype=int64)

In [37]:
#It missidentified 3
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        0.0       0.98      0.99      0.98       257
        1.0       0.98      0.97      0.98       196

avg / total       0.98      0.98      0.98       453



In [38]:
model.save('mysupermodel.h5')

In [39]:
from keras.models import load_model
newmodel = load_model('mysupermodel.h5')