In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]
type(mylist)

list

In [3]:
myArray = np.array(mylist)
myArray

array([1, 2, 3])

In [4]:
type(myArray)

numpy.ndarray

In [5]:
np.arrange(0, 10)

AttributeError: module 'numpy' has no attribute 'arrange'

In [6]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.zeros(shape=(10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones(shape=(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.random.seed(101)

In [12]:
arr = np.random.randint(0,100,10)

In [13]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [14]:
arr2 = np.random.randint(0,100,10)

In [15]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [16]:
arr.max()

95

In [17]:
arr.argmax()

0

In [18]:
arr.min()

9

In [19]:
arr.argmin()

7

In [20]:
arr.mean()

60.8

In [21]:
arr.shape

(10,)

In [22]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [23]:
arr.reshape((2,10))

ValueError: cannot reshape array of size 10 into shape (2,10)

In [24]:
mat = np.arange(0,100).reshape(10,10)

In [25]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [26]:
mat.shape

(10, 10)

In [28]:
row = 0
col = 1

In [29]:
mat[row,col]

1

In [30]:
mat[4, 6]

46

In [31]:
type(mat)

numpy.ndarray

In [32]:
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [33]:
mat[:, 1].shape

(10,)

In [34]:
mat[:, 1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [35]:
mat[0:3, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [36]:
mynewmat = mat.copy()

In [37]:
mynewmat[0:6, :] = 999

In [38]:
mynewmat

array([[999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])